<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '1.4.8';
$moduleRevision = '2b8acbeaaf36b80a63474ad6c7f2f32b6e77ad60';
$moduleWikiUrl = 'http://www.docs.modulesgarden.com/Time_Tracking_Center_For_WHMCS';